env:
  browser: true
  jest: true
parser: babel-eslint
extends: airbnb
plugins:
  - react-hooks
globals:
  DEBUG: readonly
  PRODUCTION: readonly
  RELEASE: readonly
  VERSION: readonly
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style: off
  no-prototype-builtins: warn
  no-underscore-dangle:
    - error
    - allow:
      - __REDUX_DEVTOOLS_EXTENSION_COMPOSE__
      - _id
  padded-blocks:
    - error
    - blocks: never
      classes: always
      switches: always
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
      allowUnboundThis: false
  quotes:
    - error
    - double
  template-curly-spacing:
    - error
    - always
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
      optionalDependencies: false
      peerDependencies: true
  import/prefer-default-export: warn
  jsx-a11y/click-events-have-key-events: off
  react/jsx-curly-spacing:
    - error
    - when: always
      children: true
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
